# Generated by Django 4.2.5 on 2023-09-09 11:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dest_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.account')),
                ('src_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.account')),
            ],
        ),
    ]
